//
// Created by luca on 8/20/21.
//

#ifndef POWERESP_MAIN_H
#define POWERESP_MAIN_H
#ifndef CPP_FREERTOS_NO_EXCEPTIONS
#define CPP_FREERTOS_NO_EXCEPTIONS
#endif
#ifndef POWERESP_VERSION
#define POWERESP_VERSION 20210825
#endif
#endif //POWERESP_MAIN_H
