#!/bin/sh
# This script flashes the built .elf file onto the board.
if [[ -z "${IDF_HAS_BEEN_IMPORTED}" ]]; then
export IDF_HAS_BEEN_IMPORTED=1
export IDF_PATH=~/esp/esp-idf
. $HOME/esp/esp-idf/export.sh
fi